/**
 * metadata.ts — Centralized metadata generation for all tool responses.
 *
 * Provides professional-use warnings, data freshness tracking, and source authority disclosure.
 */

import type { Database } from '@ansvar/mcp-sqlite';

export interface ResponseMetadata {
  data_freshness: DataFreshness;
  disclaimer: string;
  source_authority: SourceAuthority;
  coverage_gaps: string[];
  ai_disclosure: string;
  note?: string;
  query_strategy?: string;
}

export interface DataFreshness {
  corpus_built_at: string | null;
  staleness_warning: string | null;
}

export interface SourceAuthority {
  primary_source: string;
  authority_level: 'official' | 'community-maintained';
  verification_required: string;
}

export function generateResponseMetadata(db?: Database): ResponseMetadata {
  const dataFreshness = db ? getDataFreshness(db) : getEmptyDataFreshness();
  const sourceAuthority = getSourceAuthority();

  return {
    data_freshness: dataFreshness,
    disclaimer:
      'NOT LEGAL ADVICE. Parliamentary debate transcripts are provided for research purposes only. ' +
      'Always verify content with official Stortinget sources (stortinget.no) before professional use.',
    source_authority: sourceAuthority,
    coverage_gaps: [
      'Committee proceedings (not included in plenary Hansard)',
      'Written questions and interpellations',
      'Post-2022-05 debates (ParlaMint-NO 3.0 ends mid-2022)',
      'Linguistic annotation (only plain TEI is ingested here)'
    ],
    ai_disclosure:
      'AI-assisted parliamentary research tool. Results generated by full-text search and may contain ' +
      'errors or omissions. Human review required before professional or political research use.'
  };
}

function getEmptyDataFreshness(): DataFreshness {
  return {
    corpus_built_at: null,
    staleness_warning: 'Data freshness information unavailable'
  };
}

function getDataFreshness(db: Database): DataFreshness {
  let corpusBuiltAt: string | null = null;
  try {
    const row = db.prepare(
      `SELECT value FROM db_metadata WHERE key = 'built_at'`
    ).get() as { value: string } | undefined;
    corpusBuiltAt = row?.value ?? null;
  } catch {
    // ignore
  }

  return {
    corpus_built_at: corpusBuiltAt,
    staleness_warning: null // ParlaMint-NO is a static corpus; no staleness concern
  };
}

function getSourceAuthority(): SourceAuthority {
  return {
    primary_source:
      'CLARIN.SI ParlaMint-NO 3.0 (http://hdl.handle.net/11356/1486) — ' +
      'TEI-encoded Norwegian Storting plenary debate minutes 2000–2022, CC-BY-4.0',
    authority_level: 'official',
    verification_required:
      'Cross-check with stortinget.no for official verbatim transcripts. ' +
      'ParlaMint-NO is a research corpus derived from Stortinget open data and may contain ' +
      'encoding artefacts.'
  };
}

export interface ToolResponse<T> {
  results: T;
  _meta: ResponseMetadata;
  _truncated?: boolean;
  _hint?: string;
}
